services:
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dev_user 
      WORDPRESS_DB_PASSWORD: sail_house_dev  
      WORDPRESS_DB_NAME: sailhou1_WPRAL
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./snapshots:/var/www/html/
      - ./wp-content/plugins/sail-user-management/:/var/www/html/wp-content/plugins/sail-user-management/

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sailhou1_WPRAL
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: sail_house_dev 
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
