CREATE TABLE `sailhou1_wpral`.`sail_users`
  (
     `userid`               BIGINT NOT NULL,
     `firstname`            TEXT NOT NULL,
     `lastname`             TEXT NOT NULL,
     `email`                TEXT NOT NULL,
     `emailverified`        TEXT NOT NULL,
     `emailverificationkey` TEXT NOT NULL,
     `addrline1`            TEXT NOT NULL,
     `addrline2`            TEXT NOT NULL,
     `city`                 TEXT NOT NULL,
     `state`                TEXT NOT NULL,
     `zipcode`              TEXT NOT NULL,
     `phonenumber`          TEXT NOT NULL,
     `profilepicture`       BLOB NOT NULL,
     `gender`               TEXT NOT NULL,
     `dob`                  DATE NOT NULL,
     `contactviaemail`      BOOLEAN NOT NULL,
     `contactviatext`       BOOLEAN NOT NULL,
     `role`                 TEXT NOT NULL,
     `situation`            TEXT NOT NULL,
     `reference`            TEXT NOT NULL,
     `timeframe`            TEXT NOT NULL,
     `newsletter`           BOOLEAN NOT NULL,
     `additionalinfo`       MEDIUMTEXT NOT NULL,
     `createdon`            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     `readtermsofservice`   BOOLEAN NOT NULL,
     `isPaidMember`         BOOLEAN NOT NULL,
     `lastDuePaymentDate`   DATE,
     `familyLinkingKey`     TEXT NULL,
     `familyId`             BIGINT NULL
  )
engine = innodb; 